### ISSUE TITLE
Can't install with composer 

### ISSUE THREAD

**Issue by WeTruck** [gisforgirard/php-timecamp-api#3]
I'm trying to install through composer,

`composer require timecamp/php-timecamp-api`

It's giving this error,
![image](https://user-images.githubusercontent.com/46923165/134810280-3ec04489-9a20-455c-a969-6affd00dc84e.png)

```
 [InvalidArgumentException]
  Could not find a matching version of package timecamp/php-timecamp-api. Check the package spelling, your version co
  nstraint and that the package is available in a stability which matches your minimum-stability (stable).
```

**Comment by gisforgirard** [comment]
oops, i updated the readme to include the correct name
